## USB port
port: /dev/ttyACM0


##### Calibration ####
### accelerometer
accel_x_min: -250.0
accel_x_max: 250.0
accel_y_min: -250.0
accel_y_max: 250.0
accel_z_min: -250.0
accel_z_max: 250.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
# home
calibration_magn_use_extended: true
magn_ellipsoid_center: [96.9494, -496.163, -407.136]
magn_ellipsoid_transform: [[0.952328, -0.00650863, 0.0215618], [-0.00650863, 0.998473, 0.00863579], [0.0215618, 0.00863579, 0.939493]]

# LAB
calibration_magn_use_extended: true
magn_ellipsoid_center: [326.660, -496.281, -622.900]
magn_ellipsoid_transform: [[0.802685, -0.0987689, -0.0716192], [-0.0987689, 0.693346, 0.164869], [-0.0716192, 0.164869, 0.817372]]


# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: 0.0
gyro_average_offset_y: 0.0
gyro_average_offset_z: 0.0
